language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token: 9341d2e8a53da97e09ff18b1937cf24f431550fde363b113292b450ab68ca1ec
before_install: cd ./api
install:
  - npm install
script:
  - npm run test
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
